### ISSUE TITLE
User Image not showing in the live feed

### ISSUE THREAD

**Issue by tedempster** [ORBNETSYS/Brivo-Public#7]
<img width="696" alt="Screen Shot 2022-02-07 at 4 45 05 PM" src="https://user-images.githubusercontent.com/99220500/152878956-a637695f-b9e3-48e3-bc61-935a98369efa.png">

**Comment by EricBourque** [comment]
Tom, can you please confirm that all the user images load now?

**Comment by tedempster** [comment]
User images are posting. See attachment.

Thanks
*Tom Dempster*
*BRIVO | *Senior QA Engineer
7700 Old Georgetown Road, Suite 300 *| *Bethesda, MD 20814
*w.* brivo.com <http://www.brivo.com> *t.* @brivoinc
<http://twitter.com/BrivoInc>
*Sales Support: *1.866.MY.BRIVO  (1.866.692.7486)
*Technical Support: *1.866.BRIVO4U  (1.866.274.8648)


<https://www.brivo.com/LP/ISCEAST-2021>
